### PR TITLE
Address Divide-By-Zero in integerDivide

### PR DESCRIPTION
**Pull request by Paul-Folbrecht**
Per Damian, integerDivide with divisor zero returns zero.

### CODE REVIEW

**Comment by xuanli09** [comment]
Are you sure about this? 

`/0` is undefined mathematically, and is not zero.

Java/Scala/Go/Python will throw/raise exceptions, errors or panics.

**Comment by Paul-Folbrecht** [comment]
> Are you sure about this?
> 
> `/0` is undefined mathematically, and is not zero.
> 
> Java/Scala/Go/Python will throw/raise exceptions, errors or panics.

Those languages will throw/panic but those languages are not purely functional. Pure FP means total functions, meaning no exceptions.

That said, the proper interface here would be a Maybe result or returning NaN, as Elm does. But we can't change the interface and Scala has no Int NaN. Primitive.Int(Double.NaN.toInt) resolves to 0.

I'm open to other suggestions.

**Comment by DamianReeves** [comment]
I think we have no choice but to return 0 here. At least doing that keeps us consistent since throwing and returning a Maybe or Result is not an option in this case.

**Comment by xuanli09** [comment]
I don't think returning 0 is a good idea. The user of any divide cannot tell if the zero signifies a 0/x or x/0, unless he himself always checks the divisor before calling divide. The user might forget and continue carrying on calculations that corrupt the data.

The best would be to introduce a NaN or Option, and the second best would be to terminate a program via exception or panics even if it's "impure". 

https://softwareengineering.stackexchange.com/a/208683

**Comment by DamianReeves** [comment]
User code can always add an `safeDivide: Int -> Int -> Maybe Int`... at this point the consistency is the best as we want to maintain the "no runtime errors" guarantee.
When we get around to implementing `morphir analyze` we can setup a rule which in certain cases can outlaw the use of the int division operator which in Elm code is distinct from the float division.

**Comment by DamianReeves** [comment]
I also failed to add that I don't love this either.

**Comment by xuanli09** [comment]
I think that is best way forward @DamianReeves and check for safe usages in compilation...

Looks like there have been some very interesting discussion on this area in the elm community:
https://discourse.elm-lang.org/t/division-by-zero/5037/18
https://github.com/elm/core/issues/1072

As Justin pointed out, the only runtime exception in elm happen to be 1 % 0: 
https://github.com/elm/core/issues/377

**Comment by DamianReeves** [comment]
Sounds like I hear reluctant acceptance here.

**Comment by DamianReeves** [comment]
I see @justin-corn has approved. And @xuanli09 it sounds like you are okay with the approach outlined via `morphir analyze` in the future.

**Pull request merged**
