### PR TITLE
Feature/improve error messages

### PR DESCRIPTION
**Pull request by matthewrfellows**
A small first contribution that tweaks error messages in Morphir-Scala ErrorUtils.

### CODE REVIEW

**Comment by michelchan** [comment]
Is this still wanted?

**Comment by edwardpeters** [comment]
> Is this still wanted?

It's a trivial but useful change - those messages tripped a few people up. 90% certain the test failures are an incremental issue, not a code problem, so if a rebuild is triggered I bet it would pass.

**Comment by michelchan** [comment]
> > Is this still wanted?
> 
> It's a trivial but useful change - those messages tripped a few people up. 90% certain the test failures are an incremental issue, not a code problem, so if a rebuild is triggered I bet it would pass.

I'll update it and kick off a new build after getting some dependency upgrades merged in.

**Review by michelchan — APPROVED** [review]
lgtm

**Pull request merged**
